# Generated by Django 4.1.2 on 2022-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_about', '0004_alter_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
    ]
